# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(485, 785)
        Form.setStyleSheet("QFrame{\n"
"background-color:#000000;\n"
"}\n"
"QLabel{\n"
"font-size:25px;\n"
"font-family:\"Helvetica\";\n"
"color:#fff\n"
"}\n"
"#close-btn{\n"
"background-color:#000;\n"
"}\n"
"#function_frame{\n"
"border-bottom:1px solid #333333;\n"
"border-top-left-radius:15px;\n"
"border-top-right-radius:15px;\n"
"}\n"
"#button_frame{\n"
"border-bottom-left-radius:15px;\n"
"border-bottom-right-radius:15px;\n"
"}\n"
"#lineEdit{\n"
"background-color:#000000;\n"
"color:#fff;\n"
"border:none;\n"
"height:100px;\n"
"padding:10px 5px;\n"
"font-size:100px;\n"
"font-family:\"Segoe UI\";\n"
"}\n"
"#button_frame QPushButton{\n"
"background-color:#333333;\n"
"color:#FFF;\n"
"border-radius:50%;\n"
"height:100px;\n"
"width:100px;\n"
"font-size:50px;\n"
"font-family:\"Helvetica\";\n"
"}\n"
"\n"
"#button_frame QPushButton:pressed{\n"
"background-color:#555;\n"
"}\n"
"#button_frame QPushButton #zero_btn{\n"
"text-align:left;\n"
"padding-left:35px;\n"
"}\n"
"\n"
"#button_frame QPushButton(class=\"btn_group1\"){\n"
"background-color:#a5a5a5;\n"
"color:#020202;\n"
"font-size:45px;\n"
"\n"
"}\n"
"#button_frame QPushButton(class=\"btn_group1\"):pressed{\n"
"background-color:#d6d6d6;\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.display_frame = QtWidgets.QFrame(parent=Form)
        self.display_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.display_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.display_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.display_frame.setObjectName("display_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.display_frame)
        self.horizontalLayout.setContentsMargins(20, -1, 10, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.display_frame)
        self.label.setMaximumSize(QtCore.QSize(20, 30))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("calculator.bmp"))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.display_frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(325, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.close_button = QtWidgets.QPushButton(parent=self.display_frame)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout.addWidget(self.close_button)
        self.verticalLayout.addWidget(self.display_frame)
        self.button_frame = QtWidgets.QFrame(parent=Form)
        self.button_frame.setEnabled(False)
        self.button_frame.setStyleSheet("")
        self.button_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.button_frame.setObjectName("button_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.button_frame)
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_3.setProperty("clear", "")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 2, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 3, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 1, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 3, 3, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 4, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 3, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 3, 2, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 4, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 4, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 3, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 4, 3, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 5, 0, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 5, 1, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 5, 2, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout.addWidget(self.pushButton_21, 6, 0, 1, 2)
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 5, 3, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.button_frame)
        self.lineEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 4)
        self.pushButton_22 = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout.addWidget(self.pushButton_22, 6, 2, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 6, 3, 1, 1)
        self.verticalLayout.addWidget(self.button_frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_2.setText(_translate("Form", "Calculator"))
        self.close_button.setText(_translate("Form", "close"))
        self.pushButton_3.setText(_translate("Form", "AC"))
        self.pushButton_3.setProperty("class", _translate("Form", "btn_group1"))
        self.pushButton_5.setText(_translate("Form", "*/-"))
        self.pushButton_5.setProperty("class", _translate("Form", "btn_group1"))
        self.pushButton_8.setText(_translate("Form", "7"))
        self.pushButton_4.setText(_translate("Form", "%"))
        self.pushButton_4.setProperty("btn_group1", _translate("Form", "btn_group1"))
        self.pushButton_4.setProperty("class", _translate("Form", "btn_group1"))
        self.pushButton_7.setText(_translate("Form", "-"))
        self.pushButton_7.setProperty("class", _translate("Form", "btn_group2"))
        self.pushButton_11.setText(_translate("Form", "4"))
        self.pushButton_9.setText(_translate("Form", "8"))
        self.pushButton_10.setText(_translate("Form", "9"))
        self.pushButton_13.setText(_translate("Form", "5"))
        self.pushButton_12.setText(_translate("Form", "6"))
        self.pushButton_6.setText(_translate("Form", "."))
        self.pushButton_6.setProperty("class", _translate("Form", "btn_group2"))
        self.pushButton_14.setText(_translate("Form", "+"))
        self.pushButton_14.setProperty("class", _translate("Form", "btn_group2"))
        self.pushButton_15.setText(_translate("Form", "3"))
        self.pushButton_18.setText(_translate("Form", "2"))
        self.pushButton_17.setText(_translate("Form", "1"))
        self.pushButton_21.setText(_translate("Form", "0"))
        self.pushButton_16.setText(_translate("Form", "*"))
        self.pushButton_16.setProperty("class", _translate("Form", "btn_group2"))
        self.lineEdit.setText(_translate("Form", "0"))
        self.pushButton_22.setText(_translate("Form", "."))
        self.pushButton_19.setText(_translate("Form", "="))
        self.pushButton_19.setProperty("class", _translate("Form", "btn_group2"))
